config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match "(*path)", to: "errors#catch_all", via: :all, constraints: ->(request) { request.headers["X-CATCHALL"].to_s.casecmp?("traefik") }
  resources :errors, only: [] do
    match :not_found, on: :collection, via: :all
    match :service_unavailable, on: :collection, via: :all
  end

  resources :stacks do
    resources :services, shallow: true do
      post :duplicate, on: :member
    end
    resources :configs, shallow: true
    resources :external_services, shallow: true
    resources :frontends, shallow: true
    resources :volumes, shallow: true

    resources :environments, only: %i[new create]
    resources :deployments, shallow: true, only: %i[index new create show]

    get "templates/:name", action: :new, controller: :templates, as: :new_template
    post "templates", action: :create, controller: :templates
  end

  resources :environments, only: %i[show destroy] do
    scope module: :docker do
      resources :services, only: %i[] do
        post :restart, on: :member
        resources :logs, only: %i[index] do
          get :stream, on: :collection
        end
      end
      resources :containers, only: %i[] do
        resource :terminal, only: %i[show]
      end
    end
    resources :services, only: [] do
      resources :metrics, only: [] do
        get :requests, on: :collection
        get :response_time, on: :collection
      end
    end
  end

  resources :users, only: %i[index update destroy]
  resource :application_setting, only: %i[show update]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :stacks, only: [] do
        post :deploy, on: :member
        delete :remove, on: :member
      end
    end
  end

  get "/auth/:provider/callback", to: "sessions#create", as: :sessions_create
  get "/auth/failure", to: "sessions#failure", as: :sessions_failure

  root "stacks#index"
end

app/models/service.rb
# frozen_string_literal: true

class Service < ApplicationRecord
  enum restart_condition: { none: 0, any: 1, "on-failure": 2 }, _prefix: true
  enum rollback_failure_action: { continue: 0, pause: 1 }, _prefix: true
  enum rollback_order: { "stop-first": 0, "start-first": 1 }, _prefix: true
  enum update_failure_action: { continue: 0, pause: 1, rollback: 2 }, _prefix: true
  enum update_order: { "stop-first": 0, "start-first": 1 }, _prefix: true

  attr_encrypted :healthcheck_test, key: Rails.application.key_generator.generate_key("Service#healthcheck_test", 32)

  belongs_to :stack

  has_many :frontends, dependent: :destroy, inverse_of: :service
  has_many :config_claims, dependent: :destroy
  has_many :volume_claims, dependent: :destroy
  has_many :external_service_claims, dependent: :destroy

  scope :ordered, -> { order(Arel.sql('LOWER("services"."name") ASC')) }

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false, scope: [:stack_id] }
  validates :name, format: { with: /\A[0-9a-z\-]+\z/i }
  validates :image, presence: true
  validates :replicas, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :restart_condition, presence: true, inclusion: { in: restart_conditions.keys }
  validates :restart_delay, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :restart_window, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :rollback_parallelism, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :rollback_delay, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :rollback_failure_action, presence: true, inclusion: { in: rollback_failure_actions.keys }
  validates :rollback_monitor, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :rollback_order, presence: true, inclusion: { in: rollback_orders.keys }
  validates :update_parallelism, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :update_delay, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :update_failure_action, presence: true, inclusion: { in: update_failure_actions.keys }
  validates :update_monitor, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :update_order, presence: true, inclusion: { in: update_orders.keys }
  validates :healthcheck, inclusion: { in: [true, false] }
  validates :healthcheck_test, presence: true, if: :healthcheck?
  validates :healthcheck_interval, numericality: { only_integer: true, greater_than: 0 }, if: :healthcheck?
  validates :healthcheck_timeout, numericality: { only_integer: true, greater_than: 0 }, if: :healthcheck?
  validates :healthcheck_start_period, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, if: :healthcheck?
  validates :healthcheck_retries, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, if: :healthcheck?

  validates_associated :config_claims
  validates_associated :external_service_claims
  validates_associated :volume_claims

  accepts_nested_attributes_for :config_claims, allow_destroy: true
  accepts_nested_attributes_for :external_service_claims, allow_destroy: true
  accepts_nested_attributes_for :volume_claims, allow_destroy: true

  def duplicate
    duplicated_service = dup
    duplicated_service.name += "-clone"
    duplicated_service.volume_claims = volume_claims.map(&:dup)
    duplicated_service.config_claims = config_claims.map(&:dup)
    duplicated_service.frontends = frontends.map(&:duplicate)
    duplicated_service
  end
end

app/controllers/docker/services_controller.rb
# frozen_string_literal: true

module Docker
  class ServicesController < ApplicationController
    before_action :set_environment
    before_action :set_service

    def restart
      DockerCli.login(@stack.registry) if @stack.registry?
      DockerCli::Service.update(name: @service.id)

      redirect_to @environment, flash: { notice: t(".notice", name: @service.name) }
    end

  private

    def set_environment
      @environment = Environment.not_deleted.find(params[:environment_id])
      @stack = @environment.stack

      authorize @stack, :show?
      authorize @environment, :logs?
    end

    def set_service
      @service = @environment.docker_services.find { |service| service.id == params[:id] }

      raise ActiveRecord::RecordNotFound if @service.blank?
    end
  end
end

app/controllers/services_controller.rb
# frozen_string_literal: true

class ServicesController < ApplicationController
  before_action :set_stack, only: %i[index new create]
  before_action :set_service, only: %i[show duplicate edit update destroy]

  def index
    authorize Service, :index?

    @services = @stack.services.ordered
  end

  def show
    authorize @service, :show?
  end

  def new
    @service = @stack.services.new

    authorize @service, :create?
  end

  def edit
    authorize @service, :update?
  end

  def duplicate
    authorize @service, :duplicate?

    duplicated_service = @service.duplicate

    if duplicated_service.save
      redirect_to duplicated_service, flash: { success: t(".success") }
    else
      redirect_to @service, alert: duplicated_service.errors.full_messages.to_sentence
    end
  end

  def create
    @service = @stack.services.new(service_params)

    authorize @service, :create?

    if @service.save
      redirect_to @service, flash: { success: t(".success") }
    else
      render :new
    end
  end

  def update
    authorize @service, :update?

    if @service.update(service_params)
      redirect_to @service, flash: { success: t(".success") }
    else
      render :edit
    end
  end

  def destroy
    authorize @service, :destroy?

    if @service.destroy
      redirect_to [@service.stack, :services], flash: { success: t(".success") }
    else
      redirect_to @service, alert: t(".alert")
    end
  end

private

  def set_stack
    @stack = Stack.find(params[:stack_id])

    authorize @stack, :show?
  end

  def set_service
    @service = Service.find(params[:id])
    @stack = @service.stack

    authorize @stack, :show?
  end

  def service_params
    params.require(:service).permit(
      :name, :image, :command,
      :replicas, :restart_condition, :restart_delay, :restart_window,
      :rollback_parallelism, :rollback_delay, :rollback_failure_action, :rollback_monitor, :rollback_order,
      :update_parallelism, :update_delay, :update_failure_action, :update_monitor, :update_order,
      :healthcheck, :healthcheck_test, :healthcheck_interval, :healthcheck_timeout, :healthcheck_start_period, :healthcheck_retries,
      config_claims_attributes: %i[id config_id target _destroy],
      external_service_claims_attributes: %i[id external_service_id target _destroy],
      volume_claims_attributes: %i[id volume_id target read_only _destroy]
    )
  end
end

app/views/services/_config_claim_fields.html.slim
.nested-fields data-controller="config-select"
  .row
    .col.w-spacer-20
      = f.association :config, collection: f.object.stack.configs.ordered.group_by(&:config_type), as: :grouped_select, group_method: :last, group_label_method: :first, label: false, prompt: :translate, input_html: { "data-action": "config-select#changedOption", "data-target": "config-select.select" }
    .col
      = f.input :target, label: false, input_html: { "data-target": "config-select.input" }, hint_html: { "data-target": "config-select.hint" }, hint: ""
    .col.w-remove-button
      = link_to_remove_association "&times;".html_safe, f, class: "btn btn-danger btn-block"

app/views/services/_external_service_claim_fields.html.slim
.nested-fields data-controller="config-select"
  .row
    .col.w-spacer-20
      = f.association :external_service, collection: f.object.stack.external_services.group_by(&:service_type), as: :grouped_select, group_method: :last, group_label_method: :first, label: false, prompt: :translate, input_html: { "data-action": "config-select#changedOption", "data-target": "config-select.select" }
    .col
      = f.input :target, label: false, input_html: { "data-target": "config-select.input" }, hint_html: { "data-target": "config-select.hint" }, hint: ""
    .col.w-remove-button
      = link_to_remove_association "&times;".html_safe, f, class: "btn btn-danger btn-block"

app/views/services/_form.html.slim
= simple_form_for(shallow(@stack, @service)) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :name
  = f.input :image
  = f.input :command

  hr.divider

  = f.input :healthcheck, input_html: { "data-toggle": "collapse", "data-target": "#collapse-healthcheck" }, wrapper_html: { class: "user-select-none" }, wrapper: :custom_boolean_switch
  #collapse-healthcheck.collapse class=("show" if f.object.healthcheck?)
    = f.input :healthcheck_test, as: :string
    .row
      .col-md-3 = f.input :healthcheck_interval, append: "sec", wrapper: :input_group
      .col-md-3 = f.input :healthcheck_timeout, append: "sec", wrapper: :input_group
      .col-md-3 = f.input :healthcheck_start_period, append: "sec", wrapper: :input_group
      .col-md-3 = f.input :healthcheck_retries

  hr.divider

  = render "form_extra", f: f

  hr.divider

  h4 Configs
  #config_claims.mb-3
    = f.simple_fields_for :config_claims do |config_claim|
      = render 'config_claim_fields', f: config_claim
    .links
      = link_to_add_association 'Add config', f, :config_claims, class: "btn btn-sm btn-success"

  hr.divider

  - if Current.settings.external_services?
    h4 External services
    #external_service_claims.mb-3
      = f.simple_fields_for :external_service_claims do |external_service_claim|
        = render 'external_service_claim_fields', f: external_service_claim
      .links
        = link_to_add_association 'Add external service', f, :external_service_claims, class: "btn btn-sm btn-success"

  hr.divider

  h4 Volumes
  #volume_claims.mb-3
    = f.simple_fields_for :volume_claims do |volume_claim|
      = render 'volume_claim_fields', f: volume_claim
    .links
      = link_to_add_association 'Add volume', f, :volume_claims, class: "btn btn-sm btn-success"


  .form-actions
    - if policy(f.object.class).index?
      => link_to f.object.class.model_name.human(count: 2), [f.object.stack, f.object.class], class: "btn btn-outline-secondary"

    - if policy(f.object).destroy?
      => link_to t(:destroy), f.object, data: { confirm: t(:are_you_sure) }, method: :delete, class: "btn btn-outline-danger"

    = f.button :submit, class: "btn-primary"

  .small.text-muted.text-right.mt-1.mb-3 = t(:submit_update_later_hint)

app/views/services/_form_extra.html.slim
a.text-right.d-block.mb-3 data-toggle="collapse" href="#service-details" role="button" aria-expanded="false" aria-controls="service-details"
  | Toggle Deploy Options

#service-details.row.collapse
  .col-4
    = f.input :replicas
    = f.input :restart_condition, collection: f.object.class.restart_conditions.keys, include_blank: false, input_html: { class: "custom-select" }
    = f.input :restart_delay, append: "sec", wrapper: :input_group
    = f.input :restart_window, append: "sec", wrapper: :input_group

  .col-4
    = f.input :update_parallelism
    = f.input :update_delay, append: "sec", wrapper: :input_group
    = f.input :update_failure_action, collection: f.object.class.update_failure_actions.keys, include_blank: false
    = f.input :update_monitor, append: "sec", wrapper: :input_group
    = f.input :update_order, collection: f.object.class.update_orders.keys, include_blank: false

  .col-4
    = f.input :rollback_parallelism
    = f.input :rollback_delay, append: "sec", wrapper: :input_group
    = f.input :rollback_failure_action, collection: f.object.class.rollback_failure_actions.keys, include_blank: false
    = f.input :rollback_monitor, append: "sec", wrapper: :input_group
    = f.input :rollback_order, collection: f.object.class.rollback_orders.keys, include_blank: false

app/views/services/_metrics.html.slim
.row
  .col-xl-6
    .card.mb-3
      .card-header
        ' Requests per minute
        small.text-muted Service #{service.name}
      .card-body.p-2.pt-3
        canvas data-controller="metrics-requests" data-url=requests_environment_service_metrics_path(environment, service)

  .col-xl-6
    .card.mb-3
      .card-header
        .float-right
          span data-title="Internal response time in milliseconds (without transport encryption, etc.)" data-toggle="tooltip" = icon "question"
        ' Response time
        small.text-muted Service #{service.name}
      .card-body.p-2.pt-3
        canvas data-controller="metrics-response-time" data-url=response_time_environment_service_metrics_path(environment, service)

app/views/services/_volume_claim_fields.html.slim
.nested-fields
  .row
    .col.w-spacer-7.align-self-center
      = f.input :read_only
    .col.w-spacer-20
      = f.association :volume, collection: f.object.stack.volumes.ordered, label: false, prompt: :translate
    .col
      = f.input :target, label: false
    .col.w-remove-button
      = link_to_remove_association "&times;".html_safe, f, class: "btn btn-block btn-danger"

app/views/services/edit.html.slim
- page_heading
  h1
    => @service.stack.name
    small = t(".title")

  - if policy(@service).show?
    => link_to t(:show), @service, class: "btn btn-secondary"

== render 'form'

app/views/services/index.html.slim
- page_heading
  h1
    => @stack.name
    small = t(".title")
  - if policy(Service).create?
    = link_to t(:title, scope: %i[services new]), [:new, @stack, :service], class: "btn btn-secondary"


.table-responsive
  table.table class=Current.settings.table_class
    thead
      tr
        th = Service.human_attribute_name("name")
        th = Service.human_attribute_name("image")
        th.d-none.d-md-table-cell = Service.human_attribute_name("command")
        th = Service.human_attribute_name("replicas")
        th
        th


    tbody
      - @services.each do |service|
        tr
          td = service.name
          td.pre = service.image
          td.d-none.d-md-table-cell.pre = service.command
          td: .badge.badge-dark = service.replicas
          td.with-btn
            - if policy(service).show?
              = link_to t(:show), service, class: "btn btn-sm btn-primary"
          td.with-btn
            - if policy(service).update?
              = link_to t(:edit), edit_service_path(service), class: "btn btn-sm btn-secondary"

app/views/services/new.html.slim
- page_heading
  h1
    => @service.stack.name
    small = t(".title")

== render 'form'

app/views/services/show.html.slim
- page_heading
  h1
    => @service.stack.name
    small
      => Service.model_name.human
      => @service.name

  - if policy(@service).update?
    = link_to t(:edit), [:edit, @service], class: "btn btn-secondary"

.row.mb-3
  .col-md-6
    .card.mb-3
      .list-group.list-group-flush
        .list-group-item.d-flex.flex-column
          .small.font-weight-bold = Service.human_attribute_name("image")
          .text-muted = @service.image
        - if @service.command?
          .list-group-item.d-flex.flex-column
            .small.font-weight-bold = Service.human_attribute_name("command")
            .text-muted = @service.command

  .col-md-6
    .card.mb-3
      .card-header.d-flex.flex-row.justify-content-between.align-items-center
        = Service.human_attribute_name("healthcheck")
        - unless @service.healthcheck?
          small.font-weight-bold Disabled

      - if @service.healthcheck?
        .list-group.list-group-flush
          .list-group-item.d-flex.flex-column
            .small.font-weight-bold = Service.human_attribute_name("healthcheck_test")
            .text-muted = @service.healthcheck_test
          .list-group-item.d-flex.flex-row.justify-content-between
            .option.d-flex.flex-column.mr-3.flex-fill
              .small.font-weight-bold = Service.human_attribute_name("healthcheck_interval")
              .text-muted = number_to_duration @service.healthcheck_interval
            .option.d-flex.flex-column.mr-3.flex-fill
              .small.font-weight-bold = Service.human_attribute_name("healthcheck_timeout")
              .text-muted = number_to_duration @service.healthcheck_timeout
            .option.d-flex.flex-column.mr-3.flex-fill
              .small.font-weight-bold = Service.human_attribute_name("healthcheck_start_period")
              .text-muted = number_to_duration @service.healthcheck_start_period
            .option.d-flex.flex-column.flex-fill
              .small.font-weight-bold = Service.human_attribute_name("healthcheck_retries")
              .text-muted = @service.healthcheck_retries

.card-columns
  - if @service.frontends.any?
    .card.mb-3
      .card-header = Frontend.model_name.human(count: 2)
      .list-group.list-group-flush
        - @service.frontends.ordered.each do |frontend|
          .list-group-item.d-flex.flex-column
            .name.small
              .float-left.font-weight-bold = frontend.name
              .float-right #{Frontend.human_attribute_name("port")} #{frontend.port}
            .target.text-muted = frontend.hosts

  - if @service.volume_claims.any?
    .card.mb-3
      .card-header = Volume.model_name.human(count: 2)
      .list-group.list-group-flush
        - @service.volume_claims.ordered_by_volume.each do |claim|
          .list-group-item.d-flex.flex-column
            .name.small
              .float-left.font-weight-bold = claim.volume.name
              - if claim.read_only?
                .float-right = VolumeClaim.human_attribute_name("read_only")
            .target.text-muted = claim.target

  - if @service.config_claims.environments.any?
    .card.mb-3
      .card-header Environment variables
      .list-group.list-group-flush
        - @service.config_claims.environments.ordered.each do |claim|
          .list-group-item.d-flex.flex-column
            .target.small.font-weight-bold = claim.target
            .value.text-muted = claim.config.formatted_value

  - if @service.config_claims.secrets.any?
    .card.mb-3
      .card-header Secrets
      .list-group.list-group-flush
        - @service.config_claims.secrets.ordered.each do |claim|
          .list-group-item.d-flex.flex-column
            .name.small.font-weight-bold = claim.config.name
            .target.text-muted
              | /run/secrets/#{claim.target}

  - if @service.config_claims.configs.any?
    .card.mb-3
      .card-header Configs
      .list-group.list-group-flush
        - @service.config_claims.configs.ordered.each do |claim|
          .list-group-item.d-flex.flex-column
            .name.small.font-weight-bold = claim.config.name
            .target.text-muted = claim.target

  - if @service.external_service_claims.any?
    .card.mb-3
      .card-header External services
      .list-group.list-group-flush
        - @service.external_service_claims.each do |claim|
          .list-group-item.d-flex.flex-column
            .name.small.d-flex.justify-content-between
              .font-weight-bold = claim.external_service.name
              .text-muted
                ' Type:
                = claim.external_service.service_type
            .target.text-muted
              - if claim.external_service.minio?
                ' #{claim.target}_HOST,
                ' #{claim.target}_BUCKET,
                ' #{claim.target}_ACCESS_KEY,
                ' #{claim.target}_SECRET_KEY

.card.mb-3
  .card-header.border-bottom-0 Deploy options
  .table-responsive
    table.table.mb-0 class=Current.settings.table_class
      tr
        td
          .small.font-weight-bold = Service.human_attribute_name("replicas")
          .text-muted = @service.replicas
        td
          .small.font-weight-bold = Service.human_attribute_name("restart_condition")
          .text-muted = @service.restart_condition
        td
          .small.font-weight-bold = Service.human_attribute_name("restart_delay")
          .text-muted = number_to_duration @service.restart_delay
        td
          .small.font-weight-bold = Service.human_attribute_name("restart_window")
          .text-muted = number_to_duration @service.restart_window
        td
      tr
        td
          .small.font-weight-bold = Service.human_attribute_name("update_parallelism")
          .text-muted = @service.update_parallelism
        td
          .small.font-weight-bold = Service.human_attribute_name("update_delay")
          .text-muted = number_to_duration @service.update_delay
        td
          .small.font-weight-bold = Service.human_attribute_name("update_failure_action")
          .text-muted = @service.update_failure_action
        td
          .small.font-weight-bold = Service.human_attribute_name("update_monitor")
          .text-muted = number_to_duration @service.update_monitor
        td
          .small.font-weight-bold = Service.human_attribute_name("update_order")
          .text-muted = @service.update_order

      tr
        td
          .small.font-weight-bold = Service.human_attribute_name("rollback_parallelism")
          .text-muted = @service.rollback_parallelism
        td
          .small.font-weight-bold = Service.human_attribute_name("rollback_delay")
          .text-muted = number_to_duration @service.rollback_delay
        td
          .small.font-weight-bold = Service.human_attribute_name("rollback_failure_action")
          .text-muted = @service.rollback_failure_action
        td
          .small.font-weight-bold = Service.human_attribute_name("rollback_monitor")
          .text-muted = number_to_duration @service.rollback_monitor
        td
          .small.font-weight-bold = Service.human_attribute_name("rollback_order")
          .text-muted = @service.rollback_order

- if policy(@service).duplicate?
  => link_to 'Duplicate', [:duplicate, @service], method: :post, data: { confirm: t(:are_you_sure) }, class: "btn btn-secondary"