config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match "(*path)", to: "errors#catch_all", via: :all, constraints: ->(request) { request.headers["X-CATCHALL"].to_s.casecmp?("traefik") }
  resources :errors, only: [] do
    match :not_found, on: :collection, via: :all
    match :service_unavailable, on: :collection, via: :all
  end

  resources :stacks do
    resources :services, shallow: true do
      post :duplicate, on: :member
    end
    resources :configs, shallow: true
    resources :external_services, shallow: true
    resources :frontends, shallow: true
    resources :volumes, shallow: true

    resources :environments, only: %i[new create]
    resources :deployments, shallow: true, only: %i[index new create show]

    get "templates/:name", action: :new, controller: :templates, as: :new_template
    post "templates", action: :create, controller: :templates
  end

  resources :environments, only: %i[show destroy] do
    scope module: :docker do
      resources :services, only: %i[] do
        post :restart, on: :member
        resources :logs, only: %i[index] do
          get :stream, on: :collection
        end
      end
      resources :containers, only: %i[] do
        resource :terminal, only: %i[show]
      end
    end
    resources :services, only: [] do
      resources :metrics, only: [] do
        get :requests, on: :collection
        get :response_time, on: :collection
      end
    end
  end

  resources :users, only: %i[index update destroy]
  resource :application_setting, only: %i[show update]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :stacks, only: [] do
        post :deploy, on: :member
        delete :remove, on: :member
      end
    end
  end

  get "/auth/:provider/callback", to: "sessions#create", as: :sessions_create
  get "/auth/failure", to: "sessions#failure", as: :sessions_failure

  root "stacks#index"
end

app/models/stack.rb
# frozen_string_literal: true

class Stack < ApplicationRecord
  attr_readonly :short_name

  attribute :production_environment_name, default: -> { Current.settings.default_production_environment_name }
  attribute :default_production_node_label, default: -> { Current.settings.default_production_node_label }
  attribute :default_review_node_label, default: -> { Current.settings.default_review_node_label }

  attr_encrypted :registry_password, key: Rails.application.key_generator.generate_key("Stack#registry_password", 32)

  has_many :stack_members, dependent: :destroy
  has_many :users, through: :stack_members

  has_many :services, dependent: :destroy
  has_many :volumes, dependent: :destroy
  has_many :frontends, dependent: :destroy
  has_many :configs, dependent: :destroy
  has_many :environments, dependent: :destroy
  has_many :deployments, dependent: :destroy
  has_many :external_services, dependent: :destroy

  scope :ordered, -> { order(Arel.sql('LOWER("stacks"."name") ASC')) }

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :short_name, presence: true
  validates :short_name, uniqueness: { case_sensitive: false }
  validates :short_name, format: { with: /\A[0-9a-z\-]+\z/i }
  validates :token, presence: true
  validates :token, uniqueness: { case_sensitive: false }

  validates :production_environment_name, presence: true

  validates :registry_url, presence: true, if: :registry?
  validates :registry_username, presence: true, if: :registry?
  validates :registry_password, presence: true, if: :registry?

  validate :validate_default_node_lables

  before_validation :set_token

  def docker_name
    "#{Cargo.config.stack_prefix}_#{short_name.downcase}"
  end

  def config_options
    @config_options ||= fetch_config_options(:value)
  end

  def config_review_options
    @config_review_options ||= fetch_config_options(:review_value).compact.reverse_merge(config_options)
  end

  def registry
    {
      url: registry_url,
      username: registry_username,
      password: registry_password
    }
  end

  def registry?
    registry_url.present? || registry_username.present? || registry_password.present?
  end

  def production_environment
    environments.not_deleted.find_by(name: production_environment_name)
  end

  def fresh?
    !(services.any? || configs.any? || volumes.any?)
  end

private

  def set_token
    return if token.present?

    self.token = SecureRandom.hex(32)
  end

  def fetch_config_options(field)
    options = configs.map { |config| [config.name, config.public_send(field)] }.to_h.symbolize_keys
    options.default_proc = proc { |_, key| "%{#{key}}" }
    options
  end

  def validate_default_node_lables
    errors.add(:default_production_node_label, :inclusion) if default_production_node_label? && Current.settings.node_labels.exclude?(default_production_node_label)
    errors.add(:default_review_node_label, :inclusion) if default_review_node_label? && Current.settings.node_labels.exclude?(default_review_node_label)
  end
end

app/controllers/api/v1/stacks_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class StacksController < Api::V1::ApplicationController
      before_action :set_stack

      def deploy
        @development = @stack.deployments.new

        if @development.update deploy_params
          render json: { status: :created }, status: :created
        else
          render json: { status: :failed, errors: @development.errors.full_messages }, status: :unprocessable_entity
        end
      end

      def remove
        @environment = @stack.environments.not_deleted.find_by(name: params[:environment])

        if @environment.blank?
          render json: { status: :failed, errors: ["environment not found"] }, status: :unprocessable_entity
        elsif @environment.production?
          render json: { status: :failed, errors: ["Production environment can not be removed"] }, status: :unprocessable_entity
        elsif @environment.remove_stack
          render json: { status: :stopped }, status: :ok
        else
          render json: { status: :failed }, status: :internal_server_error
        end
      end

    private

      def set_stack
        @stack = Stack.find_by!(id: params[:id], token: request.headers["X-TOKEN"])
      end

      def deploy_params
        params.permit(:environment, :version, tags: {}, images: {})
      end
    end
  end
end

app/controllers/stacks_controller.rb
# frozen_string_literal: true

class StacksController < ApplicationController
  before_action :set_stack, only: %i[show edit update destroy]

  def index
    authorize Stack, :index?

    @stacks = Stack.ordered
  end

  def show
    authorize @stack, :show?

    @environments = @stack.environments.ordered.not_deleted.includes(:last_deployment).to_a
    @production = @environments.find(&:production?)
    @reviews = @environments.reject(&:production?)
  end

  def new
    @stack = current_user.stacks.new

    authorize @stack, :create?
  end

  def edit
    authorize @stack, :update?
  end

  def create
    @stack = Stack.new(stack_params)
    @stack.users << current_user unless @stack.users.include? current_user

    authorize @stack, :create?

    if @stack.save
      redirect_to @stack, flash: { success: t(".success") }
    else
      render :new
    end
  end

  def update
    authorize @stack, :update?

    if @stack.update(stack_params)
      redirect_to @stack, flash: { success: t(".success") }
    else
      render :edit
    end
  end

  def destroy
    authorize @stack, :destroy?

    if @stack.destroy
      redirect_to [:stacks], flash: { success: t(".success") }
    else
      redirect_to @stack, alert: t(".alert")
    end
  end

private

  def set_stack
    @stack = Stack.find(params[:id])
  end

  def stack_params
    params.require(:stack).permit(
      :name, :short_name, :production_environment_name,
      :default_production_node_label, :default_review_node_label,
      :registry_url, :registry_username, :registry_password,
      user_ids: []
    )
  end
end

app/views/stacks/_form.html.slim
= simple_form_for(@stack) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    .row
      .col-md-8 = f.input :name
      .col-md-4 = f.input :short_name, readonly: !f.object.new_record?

    = f.input :production_environment_name

    hr.divider

    .row
      .col-md-6 = f.input :default_production_node_label, collection: Current.settings.node_labels
      .col-md-6 = f.input :default_review_node_label, collection: Current.settings.node_labels

    hr.divider

    .row
      .col-12= f.input :registry_url
      .col-md-6 = f.input :registry_username
      .col-md-6 = f.input :registry_password, as: :string

    hr.divider

    - f.object.users = [f.object.users, User.admin].flatten.compact.uniq
    = f.association :users, as: :check_boxes, disabled: User.admin.map(&:id), collection: User.approved.ordered

    .form-actions
      - if policy(f.object.class).index?
        => link_to f.object.class.model_name.human(count: 2), [f.object.class], class: "btn btn-outline-secondary"

      - if policy(f.object).destroy?
        => link_to t(:destroy), f.object, data: { confirm: t(:are_you_sure) }, method: :delete, class: "btn btn-outline-danger"

      = f.button :submit, class: "btn-primary"

app/views/stacks/_gitlab_ci_modal.html.slim
.modal.fade id="#{id}" tabindex="-1" role="dialog" aria-labelledby="#{id}Label" aria-hidden="true"
  .modal-dialog.modal-dialog-centered.modal-lg role="document"
    .modal-content.bg-primary
      .modal-header.text-white
        h5.modal-title#ciModalLabel Gitlab CI Integration

        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times

      .modal-body.bg-white.rounded-bottom
        h6 CI Variables

        .row
          .col-md-6.add-double-point = copy_input "CARGO_HOST"
          .col-md-6 = copy_input root_url.chomp('/')
        .row
          .col-md-6.add-double-point = copy_input "CARGO_STACK_ID"
          .col-md-6 = copy_input @stack.id
        .row.mb-3
          .col-md-6.add-double-point = copy_input "CARGO_STACK_TOKEN"
          .col-md-6 = copy_input @stack.token

        h6 .gitlab-ci.yml
        = rouge language: :yaml, class: "mb-3"
          |
            deploy environment:
              stage: deploy
              image: nuux/cargo-cli:latest
              script: >
                cargo-cli deploy $CI_ENVIRONMENT_SLUG \
                  --version $CI_COMMIT_SHORT_SHA \
                  --tags web:$CI_COMMIT_SHORT_SHA api:$CI_COMMIT_SHORT_SHA
              environment:
                name: $CI_COMMIT_REF_NAME
                url: https://$CI_ENVIRONMENT_SLUG.#{@stack.short_name.downcase}.#{Current.settings.host}
                on_stop: stop environment

        = rouge language: :yaml
          |
            stop environment:
              stage: deploy
              image: nuux/cargo-cli:latest
              script: cargo-cli remove $CI_ENVIRONMENT_SLUG
              when: manual
              environment:
                name: $CI_COMMIT_REF_NAME
                action: stop
              except:
                - production

app/views/stacks/edit.html.slim
- page_heading
  h1 = t(".title")

  - if policy(@stack).show?
    => link_to t(:show), @stack, class: "btn btn-secondary"

== render 'form'

app/views/stacks/index.html.slim
- page_heading
  h1 = t(".title")
  - if policy(Stack).create?
    = link_to t(:title, scope: %i[stacks new]), new_stack_path, class: "btn btn-secondary"


.table-responsive
  table.table class=Current.settings.table_class
    thead
      tr
        th = Stack.human_attribute_name("name")
        th.d-none.d-sm-table-cell
        th
        th
        th

    tbody
      - @stacks.each do |stack|
        tr
          td
            - if policy(stack).show?
              = link_to stack.name, stack, class: "text-reset"
            - else
              = stack.name

          td.text-muted.text-right.d-none.d-sm-table-cell
            - if policy(stack).show?
              - if stack.production_environment&.last_deployment
                span data-toggle="tooltip" data-title="Last deployment to #{stack.production_environment_name}"
                  => time_ago_in_words stack.production_environment&.last_deployment&.updated_at
                  | ago

          td.with-btn
            - if policy(stack).show?
              .badge.badge-dark data-toggle="tooltip" data-title=Environment.model_name.human(count: 2) = stack.environments.not_deleted.count

          td.with-btn
            - if policy(stack).show?
              = link_to t(:show), stack, class: "btn btn-sm btn-primary"

          td.with-btn
            = render "environments/open", environment: stack.production_environment

app/views/stacks/new.html.slim
- page_heading
  h1 = t(".title")

== render 'form'

app/views/stacks/show.html.slim
- page_heading
  h1 = @stack.name
  button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ciModal" Gitlab CI
  - if policy(@stack).update?
    => link_to t(:edit), [:edit, @stack], class: "btn btn-secondary"

- if @production.present?
  h4.mb-3.d-flex.align-items-center
    div
      => Environment.model_name.human
      => @production.name
      => icon "star"
      small = @production.last_deployment&.version

    - if policy(@production).show?
      = link_to t(:details), @production, class: "btn btn-sm btn-outline-secondary ml-auto"

  - if @production.last_deployment
    = render "environments/metrics", environment: @production
    .card.mb-3 = render "docker/services/services", environment: @production, details: false

  - else
    .text-muted It has not been deployed yet.

  .mb-4

- if @reviews.any?
  h4.mb-3 Review environments

  - @reviews.each do |environment|
    .card.mb-3
      .card-header.d-flex.align-items-center
        div
          => Environment.model_name.human
          => environment.name
          small = environment.last_deployment&.version

        - if policy(environment).show?
          = link_to t(:details), environment, class: "btn btn-sm btn-outline-secondary ml-auto"

      - if environment.last_deployment
        = render "docker/services/services", environment: environment, details: false

      - else
        .card-body
          .text-muted It has not been deployed yet.


- if policy(@stack).template?
  .row.justify-content-center.mt-5.pt-5
    .col-lg-8.col-xl-6
      .card
        .card-body
          h5.mb-4 Import template
          table.table.mb-0 class=Current.settings.table_class
            - TemplateService.all.each do |template|
              tr
                td = t(:title, scope: [:templates, template.name])
                td.text-muted => t(:description, scope: [:templates, template.name])
                td.with-btn => link_to t(:import), stack_new_template_path(@stack, name: template.name), class: "btn btn-sm btn-secondary"

- elsif @environments.empty?
  p.text-center.text-muted.lead Stack has not been deployed yet.

= render "gitlab_ci_modal", id: "ciModal"