config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  match "(*path)", to: "errors#catch_all", via: :all, constraints: ->(request) { request.headers["X-CATCHALL"].to_s.casecmp?("traefik") }
  resources :errors, only: [] do
    match :not_found, on: :collection, via: :all
    match :service_unavailable, on: :collection, via: :all
  end

  resources :stacks do
    resources :services, shallow: true do
      post :duplicate, on: :member
    end
    resources :configs, shallow: true
    resources :external_services, shallow: true
    resources :frontends, shallow: true
    resources :volumes, shallow: true

    resources :environments, only: %i[new create]
    resources :deployments, shallow: true, only: %i[index new create show]

    get "templates/:name", action: :new, controller: :templates, as: :new_template
    post "templates", action: :create, controller: :templates
  end

  resources :environments, only: %i[show destroy] do
    scope module: :docker do
      resources :services, only: %i[] do
        post :restart, on: :member
        resources :logs, only: %i[index] do
          get :stream, on: :collection
        end
      end
      resources :containers, only: %i[] do
        resource :terminal, only: %i[show]
      end
    end
    resources :services, only: [] do
      resources :metrics, only: [] do
        get :requests, on: :collection
        get :response_time, on: :collection
      end
    end
  end

  resources :users, only: %i[index update destroy]
  resource :application_setting, only: %i[show update]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :stacks, only: [] do
        post :deploy, on: :member
        delete :remove, on: :member
      end
    end
  end

  get "/auth/:provider/callback", to: "sessions#create", as: :sessions_create
  get "/auth/failure", to: "sessions#failure", as: :sessions_failure

  root "stacks#index"
end

app/models/frontend.rb
# frozen_string_literal: true

require "ipaddr"
require "resolv"

class Frontend < ApplicationRecord
  TLS_OPTIONS = %w[modern intermediate].freeze

  attr_encrypted :auth_basic_users, key: Rails.application.key_generator.generate_key("Frontend#auth_basic_users", 32)

  belongs_to :stack, inverse_of: :frontends
  belongs_to :service, inverse_of: :frontends

  scope :ordered, -> { order(Arel.sql('LOWER("frontends"."name") ASC')) }

  attribute :ignore_wrong_dns_entries, default: "0"

  validates :name, presence: true
  validates :name, format: { with: /\A[0-9a-z\-]+\z/i }
  validates :name, uniqueness: { case_sensitive: false, scope: [:stack_id] }
  validates :name, exclusion: { in: %w[docker domain enable port tags protocol weight backend frontend] }
  validates :port, presence: true
  validates :port, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 65_535 }

  validates :redirect, inclusion: { in: [true, false] }
  validates :redirect_regex, presence: true, if: :redirect?
  validates :redirect_replacement, presence: true, if: :redirect?
  validates :redirect_permanent, inclusion: { in: [true, false] }, if: :redirect?

  validates :auth_basic, inclusion: { in: [true, false] }
  validates :auth_basic_remove_header, inclusion: { in: [true, false] }, if: :auth_basic?
  validates :auth_basic_users, presence: true, if: :auth_basic?

  validates :hsts, inclusion: { in: [true, false] }
  validates :hsts_max_age, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, if: :hsts?
  validates :hsts_include_subdomain, inclusion: { in: [true, false] }, if: :hsts?

  validates :tls, inclusion: { in: [true, false] }
  validates :tls_cert_resolver, inclusion: { in: ->(_) { Current.settings.traefik_cert_resolvers } }, if: :tls?
  validates :tls_domains, presence: true, if: -> { tls? && router_rule? }
  validates :tls_options, inclusion: { in: TLS_OPTIONS }, if: :tls?

  validate :validates_service
  validate :validates_hosts_dns_entries

  delegate :name, to: :service, prefix: true

  before_validation :set_stack

  def duplicate
    duplicated_frontend = dup
    duplicated_frontend.name += "-clone"
    duplicated_frontend
  end

  def tls_domains=(value)
    value.is_a?(String) ? super(value.split(/,|\n/).map(&:strip).compact.uniq) : super(value)
  end

  def tls_domains
    super || []
  end

private

  def set_stack
    return if stack_id.present?
    return if service.blank?

    self.stack = service.stack
  end

  def validates_service
    return if service&.new_record?

    errors.add(:service, :invalid) unless stack&.services&.include? service
  end

  def validates_hosts_dns_entries
    return if ignore_wrong_dns_entries == "1"
    return if hosts.blank?

    server_ip_addresses = resolve_ip_addresses(Current.settings.host)

    hosts.to_s.split.each do |host|
      next if host.blank?
      next if ip_addresses_match?(server_ip_addresses, resolve_ip_addresses(host))

      errors.add(:hosts, :invalid, message: "is invalid. DNS entry for \"#{host}\" seems to be wrong.")
    end
  end

  def resolve_ip_addresses(host)
    Resolv.getaddresses(host).map { |ip_address| IPAddr.new(ip_address) }
  end

  def ip_addresses_match?(ip_addresses, other_ip_addresses)
    ip_addresses.any? { |ip_address| other_ip_addresses.any? { |other_ip_address| ip_address.include?(other_ip_address) } }
  end
end

app/controllers/frontends_controller.rb
# frozen_string_literal: true

class FrontendsController < ApplicationController
  before_action :set_stack, only: %i[index new create]
  before_action :set_frontend, only: %i[show edit update destroy]

  def index
    authorize Frontend, :index?

    @frontends = @stack.frontends.ordered
  end

  def show
    authorize @frontend, :show?
  end

  def new
    @frontend = @stack.frontends.new

    authorize @frontend, :create?
  end

  def edit
    authorize @frontend, :update?
  end

  def create
    @frontend = @stack.frontends.new(frontend_params)

    authorize @frontend, :create?

    if @frontend.save
      redirect_to @frontend, flash: { success: t(".success") }
    else
      render :new
    end
  end

  def update
    authorize @frontend, :update?

    if @frontend.update(frontend_params)
      redirect_to @frontend, flash: { success: t(".success") }
    else
      render :edit
    end
  end

  def destroy
    authorize @frontend, :destroy?

    if @frontend.destroy
      redirect_to [@frontend.stack, :frontends], flash: { success: t(".success") }
    else
      redirect_to @frontend, alert: t(".alert")
    end
  end

private

  def set_stack
    @stack = Stack.find(params[:stack_id])

    authorize @stack, :show?
  end

  def set_frontend
    @frontend = Frontend.find(params[:id])
    @stack = @frontend.stack

    authorize @stack, :show?
  end

  def frontend_params
    params.require(:frontend).permit(
      :service_id,
      :name, :port, :hosts, :ignore_wrong_dns_entries, :router_rule,
      :tls, :tls_cert_resolver, :tls_domains, :tls_options,
      :redirect, :redirect_regex, :redirect_replacement, :redirect_permanent,
      :auth_basic, :auth_basic_remove_header, :auth_basic_users,
      :request_headers, :response_headers,
      :hsts, :hsts_max_age, :hsts_include_subdomain
    )
  end
end

app/views/frontends/_form.html.slim
= simple_form_for(shallow(@stack, @frontend)) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :service, collection: f.object.stack.services
    = f.input :name
    = f.input :port

    = f.input :hosts
    - if f.object.errors.include?(:hosts)
      = f.input :ignore_wrong_dns_entries, as: :boolean

    - if Current.settings.traefik_version == "v2"
      = f.input :router_rule

      hr.divider
      = f.input :tls, input_html: { "data-toggle": "collapse", "data-target": "#collapse-tls" }, wrapper_html: { class: "user-select-none" }, wrapper: :custom_boolean_switch
      #collapse-tls.collapse class=("show" if f.object.tls?)
        = f.input :tls_domains, input_html: { value: f.object.tls_domains.join("\n") }
        = f.input :tls_cert_resolver, collection: Current.settings.traefik_cert_resolvers
        = f.input :tls_options, collection: f.object.class::TLS_OPTIONS

    hr.divider
    .row
      .col-md-6 = f.input :request_headers
      .col-md-6 = f.input :response_headers
    hr.divider

    = f.input :redirect, input_html: { "data-toggle": "collapse", "data-target": "#collapse-redirect" }, wrapper_html: { class: "user-select-none" }, wrapper: :custom_boolean_switch
    #collapse-redirect.collapse class=("show" if f.object.redirect?)
      .row
        .col-md-6 = f.input :redirect_regex
        .col-md-6 = f.input :redirect_replacement
      = f.input :redirect_permanent
    hr.divider

    = f.input :auth_basic, input_html: { "data-toggle": "collapse", "data-target": "#collapse-auth-basic" }, wrapper_html: { class: "user-select-none" }, wrapper: :custom_boolean_switch
    #collapse-auth-basic.collapse class=("show" if f.object.auth_basic?)
      = f.input :auth_basic_users, as: :text
      = f.input :auth_basic_remove_header
    hr.divider

    = f.input :hsts, input_html: { "data-toggle": "collapse", "data-target": "#collapse-hsts" }, wrapper_html: { class: "user-select-none" }, wrapper: :custom_boolean_switch
    #collapse-hsts.collapse class=("show" if f.object.hsts?)
      = f.input :hsts_max_age
      = f.input :hsts_include_subdomain

  .form-actions
    - if policy(f.object.class).index?
      => link_to f.object.class.model_name.human(count: 2), [f.object.stack, f.object.class], class: "btn btn-outline-secondary"

    - if policy(f.object).destroy?
      => link_to t(:destroy), f.object, data: { confirm: t(:are_you_sure) }, method: :delete, class: "btn btn-outline-danger"

    = f.button :submit, class: "btn-primary"

  .small.text-muted.text-right.mt-1.mb-3 = t(:submit_update_later_hint)

app/views/frontends/edit.html.slim
- page_heading
  h1
    => @frontend.stack.name
    small = t(".title")

  - if policy(@frontend).show?
    => link_to t(:show), @frontend, class: "btn btn-secondary"

== render 'form'

app/views/frontends/index.html.slim
- page_heading
  h1
    => @stack.name
    small = t(".title")

  - if policy(Frontend).create?
    = link_to t(:title, scope: %i[frontends new]), [:new, @stack, :frontend], class: "btn btn-secondary"

.table-responsive
  table.table class=Current.settings.table_class
    thead
      tr
        th = Frontend.human_attribute_name("name")
        th = Frontend.human_attribute_name("service")
        th.d-none.d-md-table-cell = Frontend.human_attribute_name("port")
        th.d-none.d-sm-table-cell = Frontend.human_attribute_name("hosts")
        th
        th

    tbody
      - @frontends.each do |frontend|
        tr
          td = frontend.name
          td = frontend.service_name
          td.d-none.d-md-table-cell = frontend.port
          td.d-none.d-sm-table-cell = frontend.hosts
          td.with-btn
            - if policy(frontend).show?
               = link_to t(:show), frontend, class: "btn btn-sm btn-primary"
          td.with-btn
            - if policy(frontend).update?
               = link_to t(:edit), edit_frontend_path(frontend), class: "btn btn-sm btn-secondary"

app/views/frontends/new.html.slim
- page_heading
  h1
    => @frontend.stack.name
    small = t(".title")

== render 'form'

app/views/frontends/show.html.slim
- page_heading
  h1

    => @frontend.stack.name
    small
      => Frontend.model_name.human
      => @frontend.name

  - if policy(@frontend).update?
    = link_to t(:edit), [:edit, @frontend], class: "btn btn-secondary"

.row
  .col-md-6
    .card.mb-3
      .list-group.list-group-flush
        .list-group-item.d-flex.flex-column
          .small.font-weight-bold = Frontend.human_attribute_name("service")
          .text-muted = @frontend.service.name
        .list-group-item.d-flex.flex-column
          .small.font-weight-bold = Frontend.human_attribute_name("port")
          .text-muted = @frontend.port
        - if @frontend.hosts? && !@frontend.router_rule?
          .list-group-item.d-flex.flex-column
            .small.font-weight-bold = Frontend.human_attribute_name("hosts")
            - @frontend.hosts.split.each do |host|
              = link_to host, "//#{host}", target: :_blank, class: "text-muted"
        - if @frontend.router_rule?
          .list-group-item.d-flex.flex-column
            .small.font-weight-bold = Frontend.human_attribute_name("router_rule")
            .text-muted = @frontend.router_rule

    - if @frontend.tls? && (@frontend.tls_domains? || @frontend.tls_cert_resolver? || @frontend.tls_options?)
      .card.mb-3
        .list-group.list-group-flush
          - if @frontend.tls_domains?
            .list-group-item.d-flex.flex-column
              .small.font-weight-bold = Frontend.human_attribute_name("tls_domains")
              - @frontend.tls_domains.each do |tls_domain|
                .text-muted = tls_domain
          - if @frontend.tls_cert_resolver?
            .list-group-item.d-flex.flex-column
              .small.font-weight-bold = Frontend.human_attribute_name("tls_cert_resolver")
              .text-muted = @frontend.tls_cert_resolver
          - if @frontend.tls_options?
            .list-group-item.d-flex.flex-column
              .small.font-weight-bold = Frontend.human_attribute_name("tls_options")
              .text-muted = @frontend.tls_options
  .col-md-6
    .card.mb-3
      .list-group.list-group-flush
        - if @frontend.request_headers?
          .list-group-item.d-flex.flex-column
            .small.font-weight-bold = Frontend.human_attribute_name("request_headers")
            .text-muted = simple_format @frontend.request_headers, class: "mb-0"

        - if @frontend.response_headers?
          .list-group-item.d-flex.flex-column
            .small.font-weight-bold = Frontend.human_attribute_name("response_headers")
            .text-muted = simple_format @frontend.response_headers, class: "mb-0"

        - if @frontend.redirect?
          .list-group-item.d-flex.flex-row.justify-content-between
            .option.d-flex.flex-column.mr-3.flex-fill
              .small.font-weight-bold Redirect regex
              .text-muted = @frontend.redirect_regex
            .option.d-flex.flex-column.flex-fill
              .small.font-weight-bold Redirect replacement
              .text-muted = @frontend.redirect_replacement

        - if @frontend.auth_basic?
          .list-group-item.d-flex.flex-column
            .small.font-weight-bold Basic auth users
            .text-muted = simple_format @frontend.auth_basic_users, class: "mb-0"

        - if @frontend.hsts?
          .list-group-item.d-flex.flex-column
            .small.font-weight-bold HTTP Strict Transport Security max age
            .text-muted
              - if @frontend.hsts_max_age > 1.day
                = (@frontend.hsts_max_age / 1.day).round
                | d
              - else
                = number_to_duration @frontend.hsts_max_age